# Generated by Django 3.0.3 on 2020-03-11 12:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_ID', models.CharField(default='', max_length=3, verbose_name='Module ID')),
                ('name', models.CharField(default='', max_length=120, verbose_name='Module Name')),
                ('semester', models.CharField(choices=[('1', 1), ('2', 2)], default=1, max_length=1, verbose_name='Semester')),
                ('year', models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1904), django.core.validators.MaxValueValidator(2020)])),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_ID', models.CharField(max_length=3, unique=True, verbose_name='Teacher ID')),
                ('t_name', models.CharField(max_length=120, verbose_name='Teacher First Name')),
                ('t_last_Name', models.CharField(max_length=120, verbose_name='Teacher Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField(default=1)),
                ('module', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='RateMyProf.Module')),
                ('teacher', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='RateMyProf.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='teachers',
            field=models.ManyToManyField(to='RateMyProf.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('module_ID', 'name', 'semester', 'year')},
        ),
    ]
