# Generated by Django 3.0.3 on 2020-02-24 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professorCode', models.CharField(max_length=3)),
                ('professorName', models.CharField(max_length=50)),
                ('profRating', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')])),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleTitle', models.CharField(max_length=50)),
                ('moduleCode', models.CharField(max_length=3)),
                ('semester', models.IntegerField(choices=[(1, 'One'), (2, 'Two')])),
                ('year', models.CharField(max_length=4)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyProf.Prof')),
            ],
        ),
    ]
