# Generated by Django 3.0.3 on 2020-03-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0002_auto_20200311_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='t_ID',
            new_name='profID',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='t_last_Name',
            new_name='profLastName',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='t_name',
            new_name='profName',
        ),
    ]
