# Generated by Django 3.0.3 on 2020-02-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0002_auto_20200224_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='year',
            field=models.CharField(default='2018', max_length=4),
        ),
        migrations.AddField(
            model_name='prof',
            name='profRating',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=0),
        ),
    ]
