# Generated by Django 3.0.3 on 2020-02-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0003_auto_20200224_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleTitle', models.CharField(max_length=50)),
                ('moduleCode', models.CharField(max_length=3)),
                ('semester', models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=0)),
                ('year', models.CharField(default='2018', max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='module',
            name='year',
        ),
    ]
