# Generated by Django 3.0.3 on 2020-02-26 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0004_auto_20200224_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('moduleCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyProf.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ModuleInstance',
        ),
        migrations.RemoveField(
            model_name='prof',
            name='profRating',
        ),
        migrations.AddField(
            model_name='rating',
            name='profCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyProf.Prof'),
        ),
        migrations.AddField(
            model_name='rating',
            name='studentNAme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyProf.Student'),
        ),
    ]
