# Generated by Django 3.0.3 on 2020-02-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0007_auto_20200226_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='moduleCode',
            new_name='Module',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='profCode',
            new_name='Professor',
        ),
    ]
