# Generated by Django 3.0.3 on 2020-02-26 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0008_auto_20200226_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='Module',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='Professor',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='year',
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('Year', models.CharField(max_length=4)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyProf.Module')),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RateMyProf.Prof')),
            ],
        ),
    ]
