# Generated by Django 3.0.3 on 2020-02-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0010_auto_20200226_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleinstance',
            old_name='Module',
            new_name='ModuleTitle',
        ),
    ]
