# Generated by Django 3.0.3 on 2020-02-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0011_auto_20200226_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='moduleCode',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='prof',
            name='professorCode',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
