# Generated by Django 3.0.3 on 2020-03-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0012_auto_20200226_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_ID', models.CharField(max_length=3, unique=True, verbose_name='Teacher ID')),
                ('t_name', models.CharField(max_length=120, verbose_name='Teacher First Name')),
                ('t_last_Name', models.CharField(max_length=120, verbose_name='Teacher Last Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='studentName',
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='module_ID',
            field=models.CharField(default='', max_length=3, verbose_name='Module ID'),
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='Module Name'),
        ),
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.CharField(choices=[('1', 1), ('2', 2)], default=1, max_length=1, verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='module',
            name='year',
            field=models.CharField(default='2020', max_length=4, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='rating',
            name='Rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='RateMyProf.Module'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('module_ID', 'name', 'semester', 'year')},
        ),
        migrations.DeleteModel(
            name='ModuleInstance',
        ),
        migrations.DeleteModel(
            name='Prof',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='module',
            name='moduleCode',
        ),
        migrations.RemoveField(
            model_name='module',
            name='moduleTitle',
        ),
        migrations.AddField(
            model_name='module',
            name='teachers',
            field=models.ManyToManyField(to='RateMyProf.Teacher'),
        ),
        migrations.AddField(
            model_name='rating',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='RateMyProf.Teacher'),
        ),
    ]
