# Generated by Django 3.0.3 on 2020-03-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0013_auto_20200309_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.AlterField(
            model_name='rating',
            name='Rating',
            field=models.FloatField(default=1),
        ),
    ]
