# Generated by Django 3.0.3 on 2020-03-10 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0014_auto_20200310_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1904), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
