# Generated by Django 3.0.3 on 2020-03-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RateMyProf', '0015_auto_20200310_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_ID', models.CharField(max_length=3, unique=True, verbose_name='Professor ID')),
                ('t_name', models.CharField(max_length=120, verbose_name='Professor First Name')),
                ('t_last_Name', models.CharField(max_length=120, verbose_name='Professor Last Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='module',
            name='professors',
            field=models.ManyToManyField(to='RateMyProf.Professor'),
        ),
        migrations.AddField(
            model_name='rating',
            name='professor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='RateMyProf.Professor'),
        ),
    ]
